environment: default
spring:
  config:
    activate:
      on-profile: def
name: de
server:
  port: 8080

---

environment: testing
spring:
  config:
    activate:
      on-profile: test
name: test-YAML
server:
  port: 4000
myCustomVarTree:
  welcomeMsg: Hello form Test
enabled: true

---

environment: production
spring:
  config:
    activate:
      on-profile: prod
name: prod-YAML
server:
  port: 5000
myCustomVarTree:
  welcomeMsg: Hello form Prod
enabled: true
